server:
  port: 8890

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
  environment: test
  datacenter: GZ_IDC
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000

    
    