server:
    port: 8899
    
spring:
  application:
    name: apptest
  profiles:
    active: dev
  cloud:
    config:
      name: apptest
      profile: dev
      lable: master
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/