server:
  port: 8890

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uniqueleon/spring-cloud-demo-config
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  resources:
    add-mappings: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
         