server:
    port: 8898
    
spring:
  application:
    name: apptest2
  profiles:
    active: dev
  cloud:
    config:
      name: apptest
      profile: dev
      lable: master
      
feign:
  okhttp:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false 