server:
    port: 8898
    
spring:
  application:
    name: apptest2
  profiles:
    active: dev
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
      
  
feign:
  okhttp:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false 
  hystrix:
    enabled: true